services:
  mongo-container:
    image: arm64v8/mongo # use this for apple silicon
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
    - ${LOCAL_PATH}/mongodb/data:/data/db
    ports:
      - "27017:27017"
    command: mongod
    restart: unless-stopped
